sudo: required
language: python

env:
  global:
    - DOCKER_IMAGE=alectolytic/rpmbuilder
    - OS_ARCH=x86_64
  matrix:
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=27
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=7

services:
    - docker

install: true

script:
  - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z -e "RPM_ONLY=1 QUIET=1" ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}



before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "Akarshan Biswas"
      - git config --local user.email "akarshan.biswas@gmail.com"
      - git tag "chromium-65.0.3325.146"
      - export RELEASE_PKG_FILE=$(ls *.rpm)
      - echo "deploying $RELEASE_PKG_FILE to GitHub releases"

deploy:
   provider: releases
   api_key: "znk04eKVnRe1xisS6G3ZLA"
   file_glob: true
   file: "$RELEASE_PKG_FILE"
   skip_cleanup: true
   on:
      tags: true
